name: databricksTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.0
        with:
          python-version: 3.8
      - name: install packages
        run: pip3 install databricks-cli
        #env: 
        #  DATABRICKS_HOST: https://adb-7218565773082452.12.azuredatabricks.net
        #  DATABRICKS_TOKEN: dapie4dd601a060d8640878b2fc1a2799085
      
      - name: configure databricks CLI
        run: |
          echo ${{secrets.dbToken}} > dbToken
          databricks configure --host https://adb-7218565773082452.12.azuredatabricks.net --token-file dbToken --profile GHA
      
      - name: view files in workspace
        run: databricks workspace ls -l --profile GHA
      
      - name: copy files from repo into databricks
        #run: databricks workspace import_dir -o --profile GHA 
        run: ls ~
