name: databricksTest

on:
  workflow_dispatch:

env:
  workspaceUrl: https://adb-7218565773082452.12.azuredatabricks.net
  srcFolder: "./Shared"
  tgtFolder: "/TempShared"
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #Specify python version
      - name: Setup Python
        uses: actions/setup-python@v2.2.0
        with:
          python-version: 3.8
      #install databricks cli
      - name: install required python packages
        run: pip3 install databricks-cli
      #configure the CLI with the url and token
      - name: configure databricks CLI
        run: |
          echo ${{secrets.dbToken}} > dbToken
          databricks configure --host ${{env.workspaceUrl}} --token-file dbToken --profile GHA
      #copy files from the shared folder in the repo to the shared folder in databricks
      - name: copy files from repo into databricks
        run: databricks workspace import_dir -o --profile GHA ${{env.srcFolder}} ${{env.tgtFolder}}
      #verify files copied successfully
      - name: view files in workspace
        run: databricks workspace ls /Shared -l --profile GHA
      
